BugzillaException: inherit from Exception
The constructor for xmlrpclib.Fault requires too many arguments. Just
keep it simple and inherit from the general Exception class.